#pragma once
#include "quantum.h"

enum onec_keycodes {
    GIT_CHECKOUT = SAFE_RANGE,
    GIT_FETCH,
    GIT_BRANCH,
    ONEC_DEBUG_START,
    ONEC_DEBUG_STOP,
    ONEC_DEBUG_RESTART,
    ONEC_DEBUG_STEP_IN,
    ONEC_DEBUG_STEP_OUT,
    ONEC_DEBUG_STEP_OVER,
    ONEC_DEBUG_STEP_TO_CURSOR,
    ONEC_CFG_APPLY,
    ONEC_RUN,
    ONEC_CALC_EXPRESSION,
    ONEC_BREAKPOINTS,
    ONEC_SEACRH_BREAK
};
