#define OC_SYMBOL_GIT_FETCH "fetch"
#define OC_SYMBOL_GIT_BRANCH "new\nbranch"
#define OC_SYMBOL_GIT_CHECKOUT "check\nout"
#define OC_SYMBOL_ONEC_DEBUG_START "debug\nstart"
#define OC_SYMBOL_ONEC_DEBUG_STOP "debug\nstop"
#define OC_SYMBOL_ONEC_DEBUG_RESTART "debug\nrestart"
#define OC_SYMBOL_ONEC_DEBUG_STEP_IN "step\nin"
#define OC_SYMBOL_ONEC_DEBUG_STEP_OUT "step\nout"
#define OC_SYMBOL_ONEC_DEBUG_STEP_OVER "step\nover"
#define OC_SYMBOL_ONEC_DEBUG_STEP_TO_CURSOR "step to\ncursor"
#define OC_SYMBOL_ONEC_CFG_APPLY "cfg\napply"
#define OC_SYMBOL_ONEC_RUN "run"
#define OC_SYMBOL_ONEC_CALC_EXPRESSION "calc\nexpr"
#define OC_SYMBOL_ONEC_BREAKPOINTS "break\npoints"
#define OC_SYMBOL_ONEC_SEACRH_BREAK "search\nbreak"
